name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-get install packages
      run: sudo apt-get install autoconf-archive flex
      # maybe also needed if setting up local dev environment:
      #   make m4 gcc g++ autoconf pkg-config libtool
    - name: set files as executable
      run: cd scripts && chmod +x install_link-grammar.sh install_emsdk.sh build.sh test.sh
    - name: install link-grammar
      run: sudo ./scripts/install_link-grammar.sh
    - name: install emsdk
      run: sudo ./scripts/install_emsdk.sh
    - name: build
      run: sudo ./scripts/build.sh
    - name: test
      run: sudo ./scripts/test.sh
